sudo: false
language: python
matrix:
  include:
  - env: TEST='py.test'
    python: '2.7'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov
    script: py.test --flake8 --cov=travisci
  - env: TEST='py.test'
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov    
    script: py.test --flake8 --cov=travisci
env:
  global:
    - secure: "eg/34jLCIhFVFcxsM3SEzaQW83RNZGCfsx2eHJI3T+YZNnlRDuN3CE52+AxotLQkM/bysMvf31b9soTxHobPkEQaRSR8e0W/V+lu9Ug0EesHXjHPbydTBG5b5nQtp4XTGZDouxUn3h4l3031VmrG+j9ZmEhZ/Knm68jOQnEaBF36vDSAteGGxIgtP8e+p1W1Tilt/7q469hjvi1IOS7kcinP/Jwqw6jjq5zzaB0DWKpcYoWSHai3uvi+WgCwWJ/PF/36jkTqEjRkVx9Hg4ZfOzGXIKJANDY8sH0mndhUDhD1HFoL5Ht931qCeZioIWPQGOFWxS7sp82GXhjUOpyrMwPDFxJ9eW7XtQWX6SttLWC6zZpI+Wj9GynWfsYp3L6eBlCh0yDU9aGrZCEL2F85nq3HnmpIfgSD6KUQGOrcsHI32ok/B/8TXV+eCGf3gf7WJKvOHga1Hvjid2U9f0sGnxXpEk2ireIOAY8GYk0mPoZYx+KodgPZ/tFjYFmOAyB7N7pNmWDHRDVKt3blgPFKqGFXIlUS7207jwYsEuqd9Y1+EZB/SM03ZjKsMOLJlV5ihGe/s1x4D/wGGJNCWTmKDWCiGZDxFYdCKbcHgContRxrAhawdDtw5JS6XIn47cZJL70P0McVKOeBzeQMoLKjWyY6kzyidhuH+E6QquSs2+Y="

