sudo: false
language: python
matrix:
  include:
  - env: TEST='py.test'
    python: '2.7'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov
    script: py.test --flake8 --cov=travisci
  - env: TEST='py.test'
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov    
    script: py.test --flake8 --cov=travisci
env:
  global:
    - secure: "uhKHLg+FnYOpR4W+FqiTABwvHCosQasaDM2kVFmNMzPd6F84xnJdYBRFMqC878uZBwmZkLUjrR0WUCiAcOsSkQSZ7I6lWZyOSbkTqMM5NEVJlDX3ksm55XsYREdUUHEukCdSfuQn6KFk+C2Goh81Bicb/GKh2L+f70kB+IZZm6hRScFLkji3JabkWZMkD38ehMXOLIZiEmJqoVOgbnnFg0ZYIba1mQsW5sDYLi8SOh79jXMEHnnOHaCidQbQeo03sbzkmv7FJ1CRPRcaVEZH/neky5oLZ7UYEYiWhs/ibgEWEzqYqcGHR6ktUdu4ghB27ktdkeP2gl77sBLMoe48JpkamVtQtuezURokLQ7+O9WX2SZELYdXlUL44FOYTX/2EfAxMHvcvSgDBPbKUnWOk69Bz7PT5YtTC6EWj5ns2m5J4YvFa4EblJzyqJnRFCdsQesz3oCIP0sUGmivkbYvs4Tfi7ASGoelKjhGpZQM4osSwXgHioY7dmR5X0ArW9oqkgkl4Hk3gNQ4gchIAyeRP4/fhn/M8PGIDE2l5BKOTh36loAa/5DjL+XgYi0hMW40yfrijYJ23C+rju7VqYO4308xygFMipJs46qW+wFjIvDdIKkvqKecZNfUZ+Y1K2J/NbCOAqEshs+CgxbVwc0k1mtykTh4ens8Eqf6vCqAXWg="
