# Secrets that can be mounted by a keeper pod
# see http://kubernetes.io/docs/user-guide/secrets/

apiVersion: v1
kind: Secret
metadata:
  name: traviscisync
type: Opaque
data:
  # Each secret value must be base64 encoded.
  # e.g. `echo -n hello | base64 | pbcopy`
  github-token: FIXME
